### ISSUE TITLE
请教一下URL的访问方式

### ISSUE THREAD

**Issue by db-one** [cloverzrg/wechat-work-message-push-go#1]
@cloverzrg 你好，我容器已经部署成功，curl -X POST 的方式测试可以正常推送，但是有的环境下需要用到URL的方式来进行推送，请问怎么样可以做到

![image](https://user-images.githubusercontent.com/20243226/116349894-990cb280-a823-11eb-8ec5-8857b9ada0d5.png)

另外就是grafana的控制面板无法访问，已经设置了GrafanaWebhookUser和GrafanaWebhookPassword的两个变量值为admin，端口7610也已经映射出来了，但是打开地址127.0.0.1:7610/grafana  显示拒绝访问
大佬辛苦了，希望不忙的时候可以回复一下，非常感谢

**Comment by cloverzrg** [comment]
不同的容器之间，没有对网络进行特别设置的话，可以直接用容器名代替ip，端口为容器内端口

**Comment by db-one** [comment]
curl -X POST 的方式测试可以正常推送，但是有的环境下需要用到URL的方式来进行调用推送，请问怎么样可以做到



感谢回复，请问这个有办法做到吗

**Comment by cloverzrg** [comment]
不知道你说的URL方式什么意思，接口本质是http请求，curl 也是发起一个http请求

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/116396231-b8bdce00-a857-11eb-8a69-71601c6dfba8.png)

就比如这种方式也可以直接推送的，
http://10.0.0.1:2555/push -H 'Content-Type: application/x-www-form-urlencoded' -H 'token: 5b291163959668180' -d 'message=推送信息'
换成这样就不行
直接在LINUX命令行下输入这个是可以正常推送的
curl -X POST http://10.0.0.1:2555/push -H 'Content-Type: application/x-www-form-urlencoded' -H 'token: 5b291163959668180' -d 'message=推送信息'
tg那个直接把http输入到浏览器地址栏打开，也可以支持推送成功，微信这个如果也可以这样就方便很多了
非常感谢

**Comment by cloverzrg** [comment]
10.x.x.x是内网，外网访问不了

**Comment by db-one** [comment]
我是公网IP已经映射出去了
有DDNS

**Comment by cloverzrg** [comment]
把token和信息放在query里面，还没有这样的接口，不过这个开发起来很简单，明天帮你加个接口吧

**Comment by db-one** [comment]
OK  非常感谢   麻烦你了

**Comment by cloverzrg** [comment]
加好了，更新镜像后，使用这个接口
http://xxx/push?token=xxx&message=123&userId=xxx
userId参数可以去掉

**Comment by db-one** [comment]
好的，非常感谢，我试试

**Comment by db-one** [comment]
OK，已经可以了，非常感谢，测试正常了
