### ISSUE TITLE
Prometheus报警在Grafana不会自动推送 我是哪里没设置好

### ISSUE THREAD

**Issue by RainNameless** [cloverzrg/wechat-work-message-push-go#2]
Prometheus会报警到Grafana  Grafana有加webhook 可不会自动推送

![QQ截图20220225190341](https://user-images.githubusercontent.com/43627188/155704482-5950825d-558e-4b6d-a264-e095707a1b88.png)

![image](https://user-images.githubusercontent.com/43627188/155692789-5e47eec2-e3be-4947-8b17-bf1b07c3bfaa.png)

![微信图片_20220225185939](https://user-images.githubusercontent.com/43627188/155704039-5958d931-8ad2-4a9e-b361-0169d02e8105.jpg)

**Comment by cloverzrg** [comment]
这个要看在grafana里面报警是怎么设置的

**Comment by RainNameless** [comment]
> 这个在grafana里面的报警是怎么设置的
![QQ截图20220225232400](https://user-images.githubusercontent.com/43627188/155741168-eda34496-2906-4786-ba08-83621c1fa257.png)
都是获取cpu 内存 硬盘 然后超值就报警 我这里是为了测试设置很低 所以一定会报  
可prometheus其实也是报警的了

**Comment by RainNameless** [comment]
> 这个在grafana里面的报警是怎么设置的

我这边是想知道  你用的是zabbix 还是 prometheus 监控的报警？
还是用他们获取 用grafana设置的报警

**Comment by cloverzrg** [comment]
grafana的警报是，根据设置的定时间隔，定时执行查询语句，再比较是否满足触发报警的规则，来判断是否需要发出警报。
grafana的警报发送有一些规则的，比如默认只发送第一次的警报，和恢复后的一个通知。grafana的8.x版本的alert设置我也不太熟了，改变太大。
zabbix 和 prometheus 我不熟

**Comment by RainNameless** [comment]
嗯 谢谢你   还是没弄好  grafana8版本对报警这一块重新修改了很多东西 我去主分支问问他们好了

**Comment by RainNameless** [comment]
> grafana的警报是，根据设置的定时间隔，定时执行查询语句，再比较是否满足触发报警的规则，来判断是否需要发出警报。 grafana的警报发送有一些规则的，比如默认只发送第一次的警报，和恢复后的一个通知。grafana的8.x版本的alert设置我也不太熟了，改变太大。 zabbix 和 prometheus 我不熟

已经解决了 https://github.com/yunlzheng/prometheus-book/blob/master/alert/alert-with-wechat.md 直接在prometheus 的 alertmanager 配置里添加微信接口环境变量就可以了 

而grafana8.4里有一个官服出的wechat接口 直接选择添加机器人参数即可 不过只能在grafana设置的才会报警 怎么把其他地方配置的报警推送 这快没有查到 如果后续查到会来补 谢谢 可以关闭这个问题了
